---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ariane
  namespace: one
  labels:
    app: ariane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ariane
  template:
    metadata:
      labels:
        app: ariane
    spec:
      containers:
        - name: ariane
          image: armanfeyzi/ariane:a6b8121e
          ports:
            - containerPort: 80
